name: validate-packer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: validation

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: validate template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: '*.hcl'